Repository prgrms-web-devcourse-final-project/WEB5_7_4Please_BE, pull requests merged in 2025-07, with the labels that each got.

#9 docs(8) : swagger-ui 설정
  .gitignore
  build.gradle
  src/main/java/com/deal4u/fourplease/config/HealthController.java
  src/main/resources/application.yml
Labels: documentation

#32 feat(29) : Pagenation Common 패키지 처리
  src/main/java/com/deal4u/fourplease/domain/auction/entity/Auction.java
  src/main/java/com/deal4u/fourplease/domain/auction/entity/Product.java
  src/main/java/com/deal4u/fourplease/domain/bid/controller/BidController.java
  src/main/java/com/deal4u/fourplease/domain/bid/entity/Bid.java
  src/main/java/com/deal4u/fourplease/domain/bid/service/BidService.java
  src/main/java/com/deal4u/fourplease/domain/common/BaseDateEntity.java
  src/main/java/com/deal4u/fourplease/domain/common/PageResponse.java
  src/main/java/com/deal4u/fourplease/domain/file/entity/File.java
  src/main/java/com/deal4u/fourplease/domain/member/entity/Member.java
  src/main/java/com/deal4u/fourplease/domain/order/entity/Order.java
  src/main/java/com/deal4u/fourplease/domain/payment/entity/Payment.java
  src/main/java/com/deal4u/fourplease/domain/review/entity/Review.java
  src/main/java/com/deal4u/fourplease/domain/settlement/entity/Settlement.java
  src/main/java/com/deal4u/fourplease/domain/shipment/entity/Shipment.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/entity/Wishlist.java
  src/test/java/com/deal4u/fourplease/domain/bid/service/BidServiceIntegrationTest.java
Labels: enhancement

#30 feat(22) : 리뷰 도메인 구현
  src/main/java/com/deal4u/fourplease/domain/member/entity/Member.java
  src/main/java/com/deal4u/fourplease/domain/member/repository/MemberRepository.java
  src/main/java/com/deal4u/fourplease/domain/order/entity/Order.java
  src/main/java/com/deal4u/fourplease/domain/order/entity/Orderer.java
  src/main/java/com/deal4u/fourplease/domain/order/repository/OrderRepository.java
  src/main/java/com/deal4u/fourplease/domain/payment/repository/PaymentRepository.java
  src/main/java/com/deal4u/fourplease/domain/review/controller/ReviewController.java
  src/main/java/com/deal4u/fourplease/domain/review/dto/ReviewRequest.java
  src/main/java/com/deal4u/fourplease/domain/review/dto/ReviewResponse.java
  src/main/java/com/deal4u/fourplease/domain/review/entity/Review.java
  src/main/java/com/deal4u/fourplease/domain/review/entity/Reviewer.java
  src/main/java/com/deal4u/fourplease/domain/review/mapper/ReviewMapper.java
  src/main/java/com/deal4u/fourplease/domain/review/repository/ReviewRepository.java
  src/main/java/com/deal4u/fourplease/domain/review/service/ReviewService.java
  src/main/java/com/deal4u/fourplease/domain/review/service/package-info.java
  src/main/java/com/deal4u/fourplease/global/exception/ErrorCode.java
  src/test/java/com/deal4u/fourplease/domain/review/service/ReviewServiceTests.java
Labels: enhancement

#38 feat(27): 경매이미지 업로드 - 고지훈
  .github/workflows/ci.yml
  src/main/java/com/deal4u/fourplease/FourPleaseBeApplication.java
  src/main/java/com/deal4u/fourplease/domain/auction/controller/AuctionController.java
  src/main/java/com/deal4u/fourplease/domain/auction/dto/AuctionImageUrlResponse.java
  src/main/java/com/deal4u/fourplease/domain/auction/factory/AuctionSaveDataFactory.java
  src/main/java/com/deal4u/fourplease/domain/auction/mapper/AutionImageUrlMapper.java
  src/main/java/com/deal4u/fourplease/domain/auction/rules/DateTimeAuctionImageNameRule.java
  src/main/java/com/deal4u/fourplease/domain/auction/rules/NickNameAuctionPathRule.java
  src/main/java/com/deal4u/fourplease/domain/auction/rules/package-info.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionImageNameRule.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionPathRule.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/SaveAuctionImageService.java
  src/main/java/com/deal4u/fourplease/domain/file/config/S3Config.java
  src/main/java/com/deal4u/fourplease/domain/file/service/FileSaver.java
  src/main/java/com/deal4u/fourplease/domain/file/service/SavePath.java
  src/main/java/com/deal4u/fourplease/domain/file/service/s3/FileValidator.java
  src/main/java/com/deal4u/fourplease/domain/file/service/s3/S3FileSaver.java
  src/main/java/com/deal4u/fourplease/domain/file/type/FileType.java
  src/main/java/com/deal4u/fourplease/domain/file/type/ImageType.java
  src/main/java/com/deal4u/fourplease/global/exception/ErrorCode.java
  src/main/resources/application-ci.yml
  src/main/resources/application.yml
  src/test/java/com/deal4u/fourplease/domain/auction/controller/AuctionControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/AuctionSavePathFactoryTest.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/SaveAuctionImageServiceTest.java
  src/test/java/com/deal4u/fourplease/domain/file/service/s3/S3FileSaverTest.java
  src/test/java/com/deal4u/fourplease/domain/file/type/ImageTypeTest.java
Labels: enhancement

#46 feat(36) : 정산 스케줄러 작성 및 정산 로직 작성
  build.gradle
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionService.java
  src/main/java/com/deal4u/fourplease/domain/bid/entity/Bid.java
  src/main/java/com/deal4u/fourplease/domain/bid/repository/BidRepository.java
  src/main/java/com/deal4u/fourplease/domain/bid/service/BidService.java
  src/main/java/com/deal4u/fourplease/domain/member/repository/MemberRepository.java
  src/main/java/com/deal4u/fourplease/domain/order/service/OrderService.java
  src/main/java/com/deal4u/fourplease/domain/payment/service/PaymentService.java
  src/main/java/com/deal4u/fourplease/domain/payment/service/PaymentTransactionService.java
  src/main/java/com/deal4u/fourplease/domain/settlement/entity/Settlement.java
  src/main/java/com/deal4u/fourplease/domain/settlement/mapper/SettlementMapper.java
  src/main/java/com/deal4u/fourplease/domain/settlement/service/SettlementService.java
  src/main/java/com/deal4u/fourplease/global/exception/ErrorCode.java
  src/main/java/com/deal4u/fourplease/global/scheduler/AuctionCloseJob.java
  src/main/java/com/deal4u/fourplease/global/scheduler/AuctionScheduleService.java
  src/main/java/com/deal4u/fourplease/global/scheduler/FailedSettlementJob.java
  src/main/java/com/deal4u/fourplease/global/scheduler/FailedSettlementScheduleService.java
  src/main/java/com/deal4u/fourplease/global/scheduler/SettlementCloseJob.java
  src/main/java/com/deal4u/fourplease/global/scheduler/SettlementScheduleService.java
  src/main/java/com/deal4u/fourplease/global/scheduler/package-info.java
  src/main/resources/application-ci.yml
  src/main/resources/data-ci.sql
  src/test/java/com/deal4u/fourplease/domain/auction/service/AuctionServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/bid/service/BidServiceIntegrationTest.java
  src/test/java/com/deal4u/fourplease/domain/order/service/OrderServiceTest.java
  src/test/java/com/deal4u/fourplease/domain/review/service/ReviewServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/settlement/service/SettlementServiceTest.java
  src/test/java/com/deal4u/fourplease/global/scheduler/AuctionScheduleServiceTest.java
  src/test/java/com/deal4u/fourplease/global/scheduler/FailedSettlementScheduleServiceTest.java
  src/test/java/com/deal4u/fourplease/global/scheduler/SettlementScheduleServiceTest.java
Labels: enhancement

#60 fix(59): 페이지 디폴트 값 추가 - 정미광
  src/main/java/com/deal4u/fourplease/domain/auction/controller/AuctionController.java
  src/main/java/com/deal4u/fourplease/domain/auction/controller/SaleController.java
  src/main/java/com/deal4u/fourplease/domain/auction/dto/AuctionSearchRequest.java
  src/main/java/com/deal4u/fourplease/domain/auction/dto/SellerSaleSearchRequest.java
Labels: enhancement

#73 fix(69): api 명세서에 따라 successhandler 수정
  src/main/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandler.java
  src/test/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandlerTest.java
Labels: bug

#84 feat(83) : 관심목록 삭제 시, AuctionId를 받도록 수정
  src/main/java/com/deal4u/fourplease/domain/wishlist/controller/WishlistController.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/repository/WishlistRepository.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/service/WishlistService.java
  src/test/java/com/deal4u/fourplease/domain/wishlist/controller/WishlistControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/wishlist/service/WishlistServiceTests.java
Labels: enhancement

#89 fix(61): 다양한 오류사항들을 수정
  build.gradle
  src/main/java/com/deal4u/fourplease/config/AuthEndpoinConfig.java
  src/main/java/com/deal4u/fourplease/config/SecurityConfig.java
  src/main/java/com/deal4u/fourplease/config/WebConfig.java
  src/main/java/com/deal4u/fourplease/domain/auction/dto/BidSummaryDto.java
  src/main/java/com/deal4u/fourplease/domain/auction/entity/Address.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionSupportService.java
  src/main/java/com/deal4u/fourplease/domain/auth/controller/AuthController.java
  src/main/java/com/deal4u/fourplease/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/deal4u/fourplease/domain/bid/controller/BidController.java
  src/main/java/com/deal4u/fourplease/domain/bid/dto/BidListRequest.java
  src/main/java/com/deal4u/fourplease/domain/bid/service/BidService.java
  src/main/java/com/deal4u/fourplease/domain/common/PageResponse.java
  src/main/java/com/deal4u/fourplease/domain/member/controller/MemberController.java
  src/main/java/com/deal4u/fourplease/domain/member/service/MemberService.java
  src/main/java/com/deal4u/fourplease/domain/notification/pushnotification/controller/PushNotificationController.java
  src/main/java/com/deal4u/fourplease/domain/notification/pushnotification/repository/PushNotificationRepository.java
  src/main/java/com/deal4u/fourplease/domain/notification/pushnotification/service/PushNotificationService.java
  src/main/java/com/deal4u/fourplease/domain/order/controller/OrderController.java
  src/main/java/com/deal4u/fourplease/domain/order/entity/Order.java
  src/main/java/com/deal4u/fourplease/domain/order/repository/OrderRepository.java
  src/main/java/com/deal4u/fourplease/domain/order/service/OrderService.java
  src/main/java/com/deal4u/fourplease/domain/payment/service/PaymentTransactionService.java
  src/main/java/com/deal4u/fourplease/domain/review/controller/ReviewController.java
  src/main/java/com/deal4u/fourplease/domain/review/service/ReviewService.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/controller/WishlistController.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/entity/Wishlist.java
  src/main/java/com/deal4u/fourplease/domain/wishlist/repository/WishlistRepository.java
  src/main/resources/application.yml
  src/main/resources/data-ci.sql
  src/main/resources/data.sql
  src/test/java/com/deal4u/fourplease/acceptance/AuctionEndTest.java
  src/test/java/com/deal4u/fourplease/acceptance/AuctionTest.java
  src/test/java/com/deal4u/fourplease/acceptance/BidMinimumPriceTest.java
  src/test/java/com/deal4u/fourplease/acceptance/BidTest.java
  src/test/java/com/deal4u/fourplease/acceptance/MockMvcBaseAcceptTest.java
  src/test/java/com/deal4u/fourplease/acceptance/OrderTest.java
  src/test/java/com/deal4u/fourplease/acceptance/PaymentTest.java
  src/test/java/com/deal4u/fourplease/acceptance/WishlistTest.java
  src/test/java/com/deal4u/fourplease/domain/auction/controller/AuctionControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/controller/SaleControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/AuctionServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/ProductImageServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/ProductServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandlerTest.java
  src/test/java/com/deal4u/fourplease/domain/order/service/OrderServiceTest.java
  src/test/java/com/deal4u/fourplease/domain/review/service/ReviewServiceTests.java
  src/test/java/com/deal4u/fourplease/domain/wishlist/controller/WishlistControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/wishlist/service/WishlistServiceTests.java
  src/test/java/com/deal4u/fourplease/global/scheduler/AuctionScheduleServiceTest.java
  src/test/java/com/deal4u/fourplease/global/scheduler/SettlementScheduleServiceTest.java
  src/test/java/com/deal4u/fourplease/testutil/TestUtils.java
Labels: bug

#95 feat(94) : 상품 상세에 isWishList 항목 추가
  src/main/java/com/deal4u/fourplease/domain/auction/controller/AuctionController.java
  src/main/java/com/deal4u/fourplease/domain/auction/dto/AuctionDetailResponse.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionService.java
  src/test/java/com/deal4u/fourplease/domain/auction/controller/AuctionControllerTests.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/AuctionServiceTests.java
  src/test/java/com/deal4u/fourplease/testutil/TestUtils.java
Labels: enhancement

#99 feat(97) : 마이페이지 내 정보 API 구현 및 테스트 작성
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionService.java
  src/main/java/com/deal4u/fourplease/domain/member/mypage/controller/MyPageController.java
  src/main/java/com/deal4u/fourplease/domain/member/mypage/dto/MemberInfoResponse.java
  src/main/java/com/deal4u/fourplease/domain/member/mypage/service/MyPageMemberInfoService.java
  src/test/java/com/deal4u/fourplease/domain/member/mypage/service/MyPageMemberInfoServiceTest.java
Labels: enhancement

#111 fix(108) : 판매자 판매 내역 COUNT 수정
  src/main/java/com/deal4u/fourplease/domain/auction/repository/AuctionRepository.java
  src/main/java/com/deal4u/fourplease/domain/auction/service/AuctionService.java
  src/test/java/com/deal4u/fourplease/domain/auction/service/AuctionServiceTests.java
Labels: bug

#114 fix(93): refreshtoken이 사라지는 버그 수정 - 진주열
  src/main/java/com/deal4u/fourplease/config/AuthEndpoinConfig.java
  src/main/java/com/deal4u/fourplease/config/SecurityConfig.java
  src/main/java/com/deal4u/fourplease/domain/auth/entity/BlacklistedToken.java
  src/main/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/deal4u/fourplease/domain/auth/service/AuthService.java
  src/test/java/com/deal4u/fourplease/domain/auth/handler/Oauth2AuthenticationSuccessHandlerTest.java
  src/test/java/com/deal4u/fourplease/domain/auth/service/AuthServiceTest.java
Labels: bug
